/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Return ok when the app process is alive.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Stream
         * @description Node events as the graph runs, then the validated answer. Answer tokens are not
         *     streamed: nothing is shown before the validator passes it.
         */
        post: operations["ask_stream_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{thread_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread History */
        get: operations["thread_history_threads__thread_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tickets */
        get: operations["tickets_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_requests__request_id__receipt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give Feedback */
        post: operations["give_feedback_requests__request_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flag Answer */
        post: operations["flag_answer_requests__request_id__flag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Retrieve citations for a question. Abstains when nothing scores above threshold.
         */
        post: operations["ask_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List ingested documents visible to this role, ACL-filtered.
         */
        get: operations["list_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_evals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveBody */
        ApproveBody: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Approve */
            approve: boolean;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "filed" | "rejected";
        };
        /** AskBody */
        AskBody: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * AskRequest
         * @description POST /ask body.
         */
        AskRequest: {
            /** Question */
            question: string;
            /** Filters */
            filters?: {
                [key: string]: string;
            } | null;
        };
        /** BudgetOut */
        BudgetOut: {
            /** Spent Usd */
            spent_usd: number;
            /** Cap Usd */
            cap_usd: number;
            /**
             * Resets At
             * Format: date-time
             */
            resets_at: string;
        };
        /**
         * DocumentSummary
         * @description One row of GET /documents.
         */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source Url */
            source_url: string;
            /** Product */
            product: string;
            /** Doc Type */
            doc_type: string;
        };
        /** EvalRunOut */
        EvalRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "golden" | "redteam";
            /** Corpus Version */
            corpus_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Scores */
            scores: {
                [key: string]: unknown;
            };
            /** Cost Usd */
            cost_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackBody */
        FeedbackBody: {
            /**
             * Value
             * @enum {string}
             */
            value: "used_as_is" | "used_with_edits" | "not_used";
        };
        /** FlagBody */
        FlagBody: {
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Response model for GET /healthz.
         */
        Health: {
            /** Status */
            status: string;
        };
        /** LatestRuns */
        LatestRuns: {
            golden: components["schemas"]["EvalRunOut"] | null;
            redteam: components["schemas"]["EvalRunOut"] | null;
        };
        /** Receipt */
        Receipt: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Route */
            route: string | null;
            /** Model */
            model: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Usd */
            usd: number;
            /** Retrieval Ms */
            retrieval_ms: number | null;
            /** Rerank Ms */
            rerank_ms: number | null;
            /** Model Ms */
            model_ms: number;
            /** Total Ms */
            total_ms: number | null;
            /** Cache Hit */
            cache_hit: boolean;
            /** Calls */
            calls: components["schemas"]["UsageLine"][];
        };
        /**
         * RetrievedChunk
         * @description One reranked candidate, for the diagnostic `retrieved` view.
         */
        RetrievedChunk: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Document Title */
            document_title: string;
            /** Page */
            page: number;
            /** Score */
            score: number;
        };
        /** TicketDraft */
        TicketDraft: {
            /** Title */
            title: string;
            /** Body */
            body: string;
        };
        /** TicketOut */
        TicketOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "approved" | "rejected" | "filed";
            draft: components["schemas"]["TicketDraft"];
            /** Approver Id */
            approver_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Timings
         * @description How long each retrieval stage took, in milliseconds.
         */
        Timings: {
            /** Embed Ms */
            embed_ms: number;
            /** Retrieval Ms */
            retrieval_ms: number;
            /** Rerank Ms */
            rerank_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /** Turn */
        Turn: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** UsageLine */
        UsageLine: {
            /** Stage */
            stage: string;
            /** Alias */
            alias: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Usd */
            usd: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cache Hit */
            cache_hit: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** AskResponse */
        bas_assistant__agent__turn__AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["bas_assistant__agent__turn__Citation"][];
            /**
             * Decision
             * @enum {string}
             */
            decision: "answered" | "abstained" | "refused" | "paused" | "failed";
            /** Route */
            route: ("fast" | "strong") | null;
            /** Model */
            model: string | null;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Approval Required */
            approval_required: boolean;
            /** Ticket Id */
            ticket_id: string | null;
            /** Notes */
            notes: string[];
            /** Cache Hit */
            cache_hit: boolean;
        };
        /** Citation */
        bas_assistant__agent__turn__Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Title */
            document_title: string;
            /** Page */
            page: number;
            /** Source Url */
            source_url: string;
            /** Snippet */
            snippet: string;
        };
        /**
         * AskResponse
         * @description POST /ask response.
         */
        bas_assistant__api__ask__AskResponse: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Answer */
            answer?: null;
            /** Citations */
            citations: components["schemas"]["bas_assistant__retrieval__pipeline__Citation"][];
            /** Retrieved */
            retrieved: components["schemas"]["RetrievedChunk"][];
            /** Abstained */
            abstained: boolean;
            timings: components["schemas"]["Timings"];
        };
        /**
         * Citation
         * @description One parent-level result, for the user-facing `citations` view.
         */
        bas_assistant__retrieval__pipeline__Citation: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Document Title */
            document_title: string;
            /** Page */
            page: number;
            /** Source Url */
            source_url: string;
            /** Snippet */
            snippet: string;
            /** Passage */
            passage: string;
            /** Score */
            score: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bas_assistant__agent__turn__AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_ask_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string;
                "X-Demo-Role"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    thread_history_threads__thread_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Turn"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tickets_tickets_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_requests__request_id__receipt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
        };
    };
    give_feedback_requests__request_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flag_answer_requests__request_id__flag_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bas_assistant__api__ask__AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_evals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestRuns"];
                };
            };
        };
    };
}
